layout grafico quase OK e grafico funcionando. E round corners nessa tela. E label da semana funcionando
JoaoFloresDev/InnovateIO pull request #69
Opened 2020-06-01 19:23 UTC by pietro1704

2020-06-02 11:41 UTC, vinihiga requested changes
Tem umas coisas ali que podem acarretar bugs aleatórions (randoms) devido ao getAllInformations do Date, pois nem sempre da para pegar essas informações do iOS!

2020-06-02 11:41 UTC, vinnyhiga137 commented on App/App/Controllers/Calendar/CalendarViewController.swift
> +		}
Adicione um catch, pq há casos que o getAllInformations pode returnar um throw devido a N motivos para não ter acesso ao sistema de calendário do iOS

2020-06-02 11:41 UTC, vinnyhiga137 commented on App/App/Controllers/Calendar/CalendarViewController.swift
> +		}
Adicione um catch, pq há casos que o getAllInformations pode returnar um throw devido a N motivos para não ter acesso ao sistema de calendário do iOS

2020-06-04 12:48 UTC, vinnyhiga137 commented
Vou deixar fechado por enquanto esse PR...

2020-06-04 12:48 UTC, closed without merging